                    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.ControladorFactura;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.ConexionBD;
import modelo.Factura;
import modelo.Producto;
import modelo.Venta;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;


/**
 *
 * @author SENA
 */
public class FRMVenta extends javax.swing.JInternalFrame {
    
    ControladorFactura controladorFactura = new ControladorFactura();
    
    
    /**
     * Creates new form FRMVenta
     */
    public FRMVenta() {
        initComponents();
        
        cargarFactura();
        
    }
    
   
    
 


      

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TBLFactura = new javax.swing.JTable();
        ComboCliente = new javax.swing.JComboBox<>();
        TXTtotal = new javax.swing.JTextField();
        TXTcliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel1.setText("jLabel1");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jMenuItem1.setText("jMenuItem1");

        setClosable(true);
        setTitle("Factura");
        setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 51));
        jLabel6.setText("Factura");

        TBLFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Factura", "ID Producto", "Cantidad", "SudTotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLFactura.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                TBLFacturaMouseMoved(evt);
            }
        });
        jScrollPane6.setViewportView(TBLFactura);

        ComboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboClienteActionPerformed(evt);
            }
        });

        TXTtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTtotalActionPerformed(evt);
            }
        });

        TXTcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTclienteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(TXTcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(291, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(197, 197, 197))))
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TBLFacturaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLFacturaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TBLFacturaMouseMoved

    private void ComboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboClienteActionPerformed
        int idc = ((Factura)ComboCliente.getSelectedItem()).getIdCliente();
        Cliente micliente = new Cliente();
        micliente=micliente.buscarPorId(idc);
        TXTcliente.setText(micliente.getNombreCliente());
        
        int sudtotal = ((Factura)ComboCliente.getSelectedItem()).getSubTotal();
        TXTtotal.setText(sudtotal+"");
        
        Date fecha  = ((Factura)ComboCliente.getSelectedItem()).getFechaFactura();
        txtfecha.setText(fecha+"");
       
        
        llenarTabla2();
    }//GEN-LAST:event_ComboClienteActionPerformed

    private void TXTtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTtotalActionPerformed
    
        
    
    }//GEN-LAST:event_TXTtotalActionPerformed

    private void TXTclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTclienteActionPerformed
   
    }//GEN-LAST:event_TXTclienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Factura> ComboCliente;
    private javax.swing.JTable TBLFactura;
    private javax.swing.JTextField TXTcliente;
    private javax.swing.JTextField TXTtotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField txtfecha;
    // End of variables declaration//GEN-END:variables

   
    
   private  void cargarFactura(){
        try {      
            Factura unaFactura = new Factura();
            unaFactura.setIdFactura(0);
            ComboCliente.removeAllItems();
            ComboCliente.addItem(unaFactura);
            Iterator rs = unaFactura.listar();
            while (rs.hasNext()){        
                System.out.println("ingresa cargaae factura");
                ComboCliente.addItem((Factura) rs.next());
            }
        } catch(Exception e){
            System.out.println("error "+e.toString());
        }
    }

   public void llenarTabla2(){
        
        DefaultTableModel tabla = (DefaultTableModel) TBLFactura.getModel();
        Iterator<Venta> itfac = listar();
        Object[] filaProducto = new Object[TBLFactura.getColumnCount()];
        tabla.setRowCount(0);
        int idc = ((Factura)ComboCliente.getSelectedItem()).getIdCliente();
        
        
        
        while (itfac.hasNext()) {
            Venta unafac = itfac.next();
     
            filaProducto[0] = unafac.getIdFactura();
            filaProducto[1] = unafac.getIdProducto();
            filaProducto[2] = unafac.getCantidadProducto();
            filaProducto[3] = unafac.getValorDetalle();
            tabla.addRow(filaProducto);
        }
    }

        public Iterator<Venta> listar() {
        ArrayList<Venta> lasVentas = new ArrayList<>();
        try {
            PreparedStatement sql = ConexionBD.conexion.prepareStatement("SELECT * FROM detalle where idfactura = ? ");
            int idf = ((Factura)ComboCliente.getSelectedItem()).getIdFactura();
            sql.setInt(1, idf);
            ResultSet rs = sql.executeQuery();
            Venta unaVenta;
            while (rs.next()) {
                unaVenta = new Venta();
                
                unaVenta.setIdFactura(rs.getInt("idfactura"));
                unaVenta.setIdProducto(rs.getInt("idproducto"));
                unaVenta.setValorDetalle(rs.getInt("valordetalle"));
                unaVenta.setCantidadProducto(rs.getInt("cantidad"));
                lasVentas.add(unaVenta);
            }
        }catch (SQLException e){
            System.out.println("Error al listar facturas: "+e.toString());
        }
        return lasVentas.iterator();

    }
        
        
    
    
}
